import type { ScriptDoc } from "@/lib/scriptDoc";

export const mockScriptDoc: ScriptDoc = {
  metadata: {
    projectId: "demo-project",
    title: "Echoes on the Pier",
    format: "feature",
    genre: "Sci-Fi Drama",
    subgenres: ["Family", "Mystery"],
    logline:
      "An estranged sound designer returns home to capture the mysterious signal haunting her family's pier.",
    rating: "PG-13",
    toneKeywords: ["atmospheric", "intimate", "mysterious"],
    targetLength: {
      unit: "pages",
      value: 105,
    },
    status: "draft",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    relatedProjects: [
      {
        projectId: "doc-signal-archive",
        relationship: "inspired-by",
        title: "Signal Archive",
        notes: "Short doc exploring the original anomaly recordings.",
      },
    ],
    franchiseOriginId: "universe-reyes",
    isExtension: true,
  },
  revision: {
    id: "rev-1",
    version: "0.3.0",
    label: "Initial studio exploration",
    createdAt: "2024-01-01T00:00:00.000Z",
    createdBy: "Script Speech",
    notes: "Seeded from blueprint outline for UI exploration.",
  },
  referenceAssets: [
    {
      id: "asset-moonlight",
      title: "Moonlit tide study",
      description: "Long exposure photo of the pier with bioluminescent tide.",
      url: "https://example.com/assets/moonlight.jpg",
      thumbnailUrl: "https://example.com/assets/moonlight-thumb.jpg",
      sourceType: "link",
      tags: ["lighting", "location"],
      attribution: "J. Alvarez",
    },
    {
      id: "asset-console",
      title: "Analog mixing console",
      description: "Reference board for the studio flashback.",
      url: "https://example.com/assets/console.png",
      thumbnailUrl: "https://example.com/assets/console-thumb.png",
      sourceType: "upload",
      tags: ["prop"],
      attribution: "Set design team",
    },
  ],
  characters: [
    {
      id: "char-mara",
      name: "Mara Reyes",
      description: "Gifted sound designer navigating grief and rediscovery.",
      pronouns: "she/her",
      archetype: "Reluctant prodigy",
      goal: "Decode the signal and reconcile with her brother.",
      arc: "From avoidance to embrace of her family's legacy.",
      voiceNotes: "Measured, observant, occasionally wry.",
      referenceAssetIds: ["asset-console"],
    },
    {
      id: "char-luis",
      name: "Luis Reyes",
      description: "Brother safeguarding the pier and its secrets.",
      pronouns: "he/him",
      archetype: "Guardian",
      goal: "Protect the pier from corporate buyout.",
      arc: "Learns to trust Mara's instincts again.",
      referenceAssetIds: ["asset-moonlight"],
    },
  ],
  locations: [
    {
      id: "loc-pier",
      name: "Reyes Family Pier",
      description: "Weathered pier with experimental hydrophones installed.",
      type: "mixed",
      sensoryNotes: "Salt, creaking wood, distant foghorns.",
      referenceAssetIds: ["asset-moonlight"],
    },
    {
      id: "loc-studio",
      name: "Abandoned Mix Studio",
      description: "Dusty analog setup with walls of cassette archives.",
      type: "interior",
      referenceAssetIds: ["asset-console"],
    },
  ],
  props: [
    {
      id: "prop-recorder",
      name: "Custom field recorder",
      description: "Mara's modded recorder capable of capturing subsonic layers.",
      purpose: "Records the anomaly",
      isCritical: true,
      referenceAssetIds: ["asset-console"],
    },
  ],
  beats: [
    {
      id: "beat-setup",
      order: 0,
      title: "Return to the pier",
      summary:
        "Mara arrives and senses something off as hydrophones hum with residual signal.",
      intent: "Reunite siblings and establish the anomaly.",
      spotlightCharacterIds: ["char-mara", "char-luis"],
      locationIds: ["loc-pier"],
      referenceAssetIds: ["asset-moonlight"],
      durationSeconds: 180,
      sceneIds: ["scene-arrival"],
    },
    {
      id: "beat-investigation",
      order: 1,
      title: "Signal patterns emerge",
      summary:
        "Late-night recording session reveals rhythmic signal echoing Mara's childhood lullaby.",
      intent: "Deepen mystery and show Mara's obsession.",
      spotlightCharacterIds: ["char-mara"],
      locationIds: ["loc-studio"],
      referenceAssetIds: ["asset-console"],
      durationSeconds: 240,
      sceneIds: ["scene-recording"],
    },
    {
      id: "beat-revelation",
      order: 2,
      title: "Pier awakens",
      summary:
        "Signal triggers light swell across the water revealing submerged array Mara never knew existed.",
      intent: "Promise of deeper family secret.",
      spotlightCharacterIds: ["char-mara", "char-luis"],
      locationIds: ["loc-pier"],
      referenceAssetIds: ["asset-moonlight"],
      durationSeconds: 210,
      sceneIds: ["scene-reveal"],
    },
  ],
  scenes: [
    {
      id: "scene-arrival",
      order: 0,
      title: "Arrival",
      summary: "Mara steps onto the pier as hydrophones thrum underneath.",
      setting: "Exterior - Reyes Pier - Night",
      pageLength: 2,
      scriptText: "INT. REYES PIER - NIGHT\nMara listens as the pier hums with energy...",
      beats: ["beat-setup"],
      elements: [],
    },
    {
      id: "scene-recording",
      order: 1,
      title: "Midnight recording",
      summary: "Mara records new signal patterns inside the abandoned studio.",
      setting: "Interior - Abandoned Studio - Night",
      pageLength: 3,
      scriptText: "INT. ABANDONED STUDIO - NIGHT\nDust swirls as reels spin up...",
      beats: ["beat-investigation"],
      elements: [],
    },
    {
      id: "scene-reveal",
      order: 2,
      title: "Luminous reveal",
      summary: "A submerged array illuminates beneath the waves.",
      setting: "Exterior - Reyes Pier - Dawn",
      pageLength: 3,
      scriptText: "EXT. REYES PIER - DAWN\nWater glows as Mara realizes the array is alive...",
      beats: ["beat-revelation"],
      elements: [],
    },
  ],
  conceptAnalysis: {
    themes: ["family", "mystery", "technology vs. nature"],
    tone: "Atmospheric blend of sci-fi mystery and intimate family drama.",
    inspirations: ["Annihilation", "Arrival", "The Leftovers"],
    emotionalPromise: "A cathartic rediscovery of family legacy through sound.",
  },
};
